fix(workflow): comprobar de nuevoq ue funciona el workflow

diff --git a/.github/workflows/auto-create-issues.yml b/.github/workflows/auto-create-issues.yml
--- a/.github/workflows/auto-create-issues.yml
+++ b/.github/workflows/auto-create-issues.yml
@@ -30,14 +30,18 @@ jobs:
           
           # Instalar dependencias
           pip install -r requirements.txt
-          
+          pip install -e ./
 
-      - name: Initialice app
+      - name: Initialize Application
         id: run-app
         run: |
-          # Iniciar la aplicación Flask
-          flask run --host=0.0.0.0 --reload --debug > app.log 2>&1 || echo "Initialization failed" > error.log
-                    
+          # Iniciar la aplicación Flask en segundo plano
+          nohup flask run --host=0.0.0.0 --reload --debug > app.log 2>&1 &
+          sleep 5
+          
+          # Verificar si la aplicación está corriendo correctamente
+          curl -f http://localhost:5000 || echo "Initialization failed" > error.log
+          
           # Verificar si hay errores
           if [ -s error.log ]; then
             echo "error=true" >> $GITHUB_ENV
@@ -56,3 +60,10 @@ jobs:
             bug
             help wanted
             high
+
+      - name: Print logs
+        if: ${{ steps.run-app.outputs.error == 'true' }}
+        run: |
+          echo "Initialization failed. Printing logs:"
+          cat error.log
+          cat app.log
